let currencies = [
  {name:'人民币',code:'CNY',symbol:'￥',isCheck:1,flag:'cn'},
  {name:'美元',code:'USD',symbol:'$',isCheck:1,flag:'us'},
  {name:'欧元',code:'EUR',symbol:'€',isCheck:1,flag:'eu'},
  {name:'英镑',code:'GBP',symbol:'£',isCheck:0,flag:'gb'},
  {name:'日元',code:'JPY',symbol:'¥',isCheck:0,flag:'jp'},
  {name:'澳大利亚元',code:'AUD',symbol:'$',isCheck:0,flag:'au'},
  {name:'加拿大元',code:'CAD',symbol:'$',isCheck:0,flag:'ca'},
  {name:'瑞士法郎',code:'CHF',symbol:'Fr',isCheck:0,flag:'ch'},
  {name:'瑞典克朗',code:'	SEK',symbol:'kr',isCheck:0,flag:'se'},
  {name:'新西兰元',code:'NZD',symbol:'$',isCheck:0,flag:'nz'},
  {name:'墨西哥比索',code:'MXN',symbol:'$',isCheck:0,flag:'mx'},
  {name:'新加坡元',code:'SGD',symbol:'$',isCheck:0,flag:'sg'},
  {name:'港元',code:'HKD',symbol:'$',isCheck:0,flag:'hk'},
  {name:'挪威克朗',code:'NOK',symbol:'kr',isCheck:0,flag:'no'},
  {name:'韩元',code:'KRW',symbol:'₩',isCheck:0,flag:'kr'},
  {name:'土耳其里拉',code:'TRY',symbol:'₤',isCheck:0,flag:'tr'},
  {name:'俄罗斯卢布',code:'RUB',symbol:'₽',isCheck:0,flag:'ru'},
  {name:'印度卢比',code:'INR',symbol:'₨',isCheck:0,flag:'in'},
  {name:'巴西雷亚尔',code:'BRL',symbol:'R$',isCheck:0,flag:'br'},
  {name:'南非兰特',code:'ZAR',symbol:'R',isCheck:0,flag:'za'},
  {name:'菲律宾比索',code:'PHP',symbol:'₱',isCheck:0,flag:'ph'},
  {name:'捷克克朗',code:'	CZK',symbol:'Kč',isCheck:0,flag:'cz'},
  {name:'印尼盾',code:'IDR',symbol:'₨',isCheck:0,flag:'id'},
  {name:'马来西亚林吉特',code:'MYR',symbol:'RM',isCheck:0,flag:'my'},
  {name:'匈牙利福林',code:'HUF',symbol:'Ft',isCheck:0,flag:'hu'},
  {name:'冰岛克朗',code:'ISK',symbol:'kr',isCheck:0,flag:'is'},
  {name:'克罗地亚库纳',code:'HRK',symbol:'kn',isCheck:0,flag:'hr'},
  {name:'保加利亚列弗',code:'BGN',symbol:'лв',isCheck:0,flag:'bg'},
  {name:'罗马尼亚列伊',code:'RON',symbol:'L',isCheck:0,flag:'ro'},
  {name:'丹麦克朗',code:'DKK',symbol:'kr',isCheck:0,flag:'dk'},
  {name:'泰铢',code:'THB',symbol:'฿',isCheck:0,flag:'th'},
  {name:'越南盾',code:'VND',symbol:'₫',isCheck:0,flag:'vn'},
]